//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Jouwal.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_Activities_View             101
#define IDD_JOUWAL_DIALOG               102
#define IDD_Villages_VIEW               103
#define IDD_HOME_VIEW                   106
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       136
#define IDI_ICON2                       137
#define IDB_PNG1                        140
#define IDB_PNG2                        141
#define IDB_BITMAP1                     147
#define IDB_BITMAP2                     149
#define IDD_ACTIVITES_ADD_VIEW          151
#define IDD_ACTIVITIES_DELETE_DIALOG    152
#define IDD_FORMVIEW                    153
#define IDD_DRAWER_VIEW                 153
#define IDB_BITMAP3                     161
#define IDI_ICON3                       162
#define IDI_ICON4                       163
#define IDI_ICON5                       164
#define IDD_SETTINGS                    165
#define IDD_EDIT_ACTIVITY_DIALOG        168
#define IDD_ACTIVITY_DELETE             170
#define IDD_VILLAGE_CREATE              174
#define IDI_ICON6                       176
#define IDD_VILLAGE_DELETE              177
#define IDD_VILLAGE_EDIT                179
#define IDD_LANGUAGES_View              180
#define IDD_Language_Create             181
#define IDD_Countries_View              182
#define IDI_ICON7                       182
#define IDD_Country_Create              183
#define IDI_ICON8                       183
#define IDD_Continent_View              184
#define IDI_ICON9                       184
#define IDD_Continent_Create            185
#define IDI_ICON10                      185
#define IDI_ICON11                      186
#define IDI_ICON12                      187
#define IDI_ICON13                      188
#define IDI_ICON14                      189
#define IDI_ICON15                      190
#define IDI_ICON16                      191
#define IDI_ICON17                      192
#define IDI_ICON18                      193
#define IDI_ICON19                      194
#define IDI_ICON20                      195
#define IDC_BUTTON2                     1009
#define IDC_BUTTON3                     1010
#define IDC_Activities                  1012
#define IDC_INKPICTURE3                 1013
#define IDC_INKPICTURE4                 1014
#define IDC_INKPICTURE6                 1016
#define IDC_MFCBUTTON1                  1017
#define IDC_HOME                        1017
#define IDC_ADD_ACTIVITIE               1017
#define IDC_ACTIVITY_CREATE             1017
#define IDC_DBCREATE                    1017
#define IDC_ADD_ACTIVITY_TO_VILLAGE     1017
#define IDC_VILLAGE_EDIT_BUTTON         1017
#define IDC_HOME2                       1018
#define IDC_HOME3                       1019
#define IDC_VILLAGES                    1019
#define IDC_HOME4                       1020
#define IDC_QUIT                        1020
#define IDC_HOME5                       1021
#define IDC_COUNTRIES                   1021
#define IDC_HOME6                       1022
#define IDC_CONTINENTS                  1022
#define IDC_HOME7                       1023
#define IDC_SETTINGS                    1023
#define IDC_INKPICTURE1                 1024
#define IDC_LANGUAGES                   1025
#define IDC_VIEWCONTROL                 1027
#define IDC_ACTIVITIES_LIST             1029
#define IDC_SEARCH_ACTIVITIE_FIELD      1030
#define IDC_DELETE_ONE_ACTIVITIE        1032
#define IDC_DELETE_ALL_ACTIVITIES       1033
#define IDC_SEARCH_ACTIVITIES_BUTTON    1034
#define IDC_EDIT_ACTIVITIE              1035
#define IDC_DESIGNATION_FIELD           1036
#define IDC_DESIGNATION_TEXT            1037
#define IDC_VILLAGE_ACTIVITE_FIELD      1038
#define IDC_VILLAGE_NUMBER_FIELD_ACTIVITY 1038
#define IDC_EDIT1                       1039
#define IDC_ACTIVITY_CANCEL             1041
#define IDC_ACTIVITY_CREATE_GROUP_BOX   1042
#define IDC_CANCEL_DELETE_ACTIVITY      1043
#define IDC_ACTIVITY_VILLAGE_NUMBER     1044
#define IDC_SEARCH_ACTIVITY_VILLAGE_NUMBER 1044
#define IDC_STATIC_TEXT_ACTIVITY_VILLAGE_NUMBER 1045
#define IDC_STATIC_ACTIVITY_NUMBER      1046
#define IDC_STATIC_ACTIVITY_NUMBER2     1047
#define IDC_DRAWER                      1048
#define IDC_HOME_WELCOM_IMAGE           1049
#define IDC_FONTCHANGER                 1051
#define IDC_REFRESH                     1052
#define IDC_VILAGE_NUMBER_ACTIVITY      1053
#define IDC_VILLAGE_NUMBER              1054
#define IDC_EDIT_ACTIVITY_BUTTON        1055
#define IDC_ACTIVITY_NUMBER_TEXT        1056
#define IDC_ACTIVITY_NUMBER_EDIT_FIELD  1057
#define IDC_DESIGNATION_ACTIVITY_EDIT_FIELD 1058
#define IDO_ACTIVITY_DELETE_BUTTON      1059
#define IDC_ACTIVITY_DELETE_NUMBER      1060
#define IDC_STATIC_VILLAGE_NUMBER       1061
#define IDC_SEARCH_VILLAGE_FIELD        1062
#define IDC_SEARCH_VILLAGES_BUTTON      1063
#define IDC_DELETE_ONE_VILLAGE          1064
#define IDC_DELETE_ALL_VILLAGES         1065
#define IDC_EDIT_VILLAGE                1066
#define IDC_ADD_VILLAGE                 1067
#define IDC_VILLAGES_LIST               1068
#define IDC_EDIT_ACTIVITY_VILLAGE       1069
#define IDC_REMOVE_ACTIVITY             1070
#define IDC_MFCBUTTON2                  1071
#define IDC_SHOW_ACTIVITY               1071
#define IDC_add_language_to_village     1071
#define IDC_VILLAGE_PAYS                1072
#define IDC_VILLAGE_PAYS_NUMBER         1072
#define IDO_CREATE                      1073
#define IDC_VILLAGE_NAME_CREATE_FIELD   1075
#define IDO_VILLAGE_DELETE              1076
#define IDC_VILLAGE_NUMBER_FIELD        1077
#define IDC_VILLAGE_COUNTRY_NUMBER_FIELD 1078
#define IDC_VILLAGE_ACTIVITY_LIST       1081
#define IDC_VILLAGE_LANGUAGES_LIST      1082
#define IDC_MFCBUTTON3                  1083
#define IDC_remove_Language_from_village 1083
#define IDC_ACTIVITY_NUMBER_FIELD       1084
#define IDC_MFCBUTTON4                  1085
#define IDC_add_aactivity_to_village_button 1085
#define IDC_MFCBUTTON5                  1086
#define IDC_remove_activity_from_village 1086
#define IDC_GRATUITE_FIELD              1087
#define IDC_VILLAGE_NAME_FIELD          1089
#define IDC_LANGUAGE_NUMBER_FIELD       1091
#define IDC_ADD                         1092
#define IDC_EDIT                        1093
#define IDC_DELETE_ONE                  1094
#define IDC_DELETE_ALL                  1095
#define IDC_SEARCH                      1096
#define IDC_SEARCH_languages_FIELD      1097
#define IDC_languages_LIST              1098
#define IDC_CREATE                      1099
#define IDC_language_DESIGNATION_FIELD  1100
#define IDC_VILLAGE_NUMBER_FIELD_Language 1101
#define IDC_SEARCH_Countries_FIELD      1102
#define IDC_SEARCH_Countries_BUTTON     1103
#define IDC_EDIT_Country                1104
#define IDC_ADD_Country                 1105
#define IDC_Countries_LIST              1106
#define IDC_Nom_TEXT                    1107
#define IDC_SEARCH_Countries__Continent_FIELD2 1107
#define IDC_SEARCH_Countries__Continent_FIELD 1107
#define IDC_Nom_FIELD                   1108
#define IDC_Continent_Number_Field      1109
#define IDC_SEARCH_Continent_FIELD      1109
#define IDC_Nom_TEXT2                   1110
#define IDC_SEARCH_Contienents_BUTTON   1110
#define IDC_EDIT_Continent              1111
#define IDC_ADD_Continent               1112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        196
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
